TOPLEVEL_LANG = verilog
SIM = modelsim
TOPLEVEL = my_module
MODULE = test_my_module
VERILOG_SOURCES = ../rtl/my_module.sv ../rtl/drowsiness_feature_memory.sv
WAVES = 1
include $(shell cocotb-config --makefiles)/Makefile.sim
